package com.slr.app.models;
// Generated Mar 27, 2021 5:30:49 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.search.mapper.pojo.mapping.definition.annotation.FullTextField;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.GenericField;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "countries", schema = "slr")
@Embeddable
public class Countries implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private long id;
	
	@Column(name = "country_name", nullable = false)
	@FullTextField(analyzer = "english_analyzer")
	private String countryName;
	
	@GenericField
	private String code;
	
	private Date createdAt;
	
	@Column(name = "code_alpha", length = 5)
	@GenericField
	private String codeAlpha;
	
	@OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "countries")
	private Set<Organizations> organizations = new HashSet<Organizations>(0);

	public Countries() {
	}

	public Countries(long id, String countryName) {
		this.id = id;
		this.countryName = countryName;
	}

	public Countries(long id, String countryName, String code, Date createdAt,String codeAlpha, Set<Organizations> organizations) {
		this.id = id;
		this.countryName = countryName;
		this.code = code;
		this.createdAt = createdAt;
		this.codeAlpha = codeAlpha;
		this.organizations = organizations;
	}


	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "code", length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getCodeAlpha() {
		return codeAlpha;
	}

	public void setCodeAlpha(String codeAlpha) {
		this.codeAlpha = codeAlpha;
	}
	
	@JsonIgnore
	public Set<Organizations> getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set<Organizations> institutionses) {
		this.organizations = institutionses;
	}

}
