package com.slr.app.models;
// Generated Jun 22, 2020, 3:24:17 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
/**
 * Editions generated by hbm2java
 */
@Entity
@Table(name = "editions", schema = "slr")
@JsonIgnoreProperties({"hibernateLazyinitializer","handler"})
public class Editions implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private long id;
	
	//@ManyToOne(fetch = FetchType.LAZY)
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "conference_id")
	private Conferences conferences;
	
	//@ManyToOne(fetch = FetchType.LAZY)
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "journal_id")
	private Journals journals;
	
	
	@Column(name = "publisher_name", length = 500)
	private String publisherName;
	
	private String volume;
	
	private String number;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "editions")
	private Set<ConferenceEditorials> conferenceEditorialses = new HashSet<ConferenceEditorials>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "editions")
	private Set<ConferencePapers> conferencePaperses = new HashSet<ConferencePapers>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "editions")
	private Set<JournalEditorials> journalEditorialses = new HashSet<JournalEditorials>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "editions")
	private Set<JournalPapers> journalPaperses = new HashSet<JournalPapers>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "editions")
	private Set<BookChapters> bookChapterses = new HashSet<BookChapters>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "editions")
	private Set<Books> bookses = new HashSet<Books>(0);
	
	
	public Editions() {
	}

	public Editions(long id) {
		this.id = id;
	}

	public Editions(long id, Conferences conferences, Journals journals, String publisherName, String volume,
			String number, Set<BookChapters> bookChapterses, Set<Books> bookses,
			Set<ConferenceEditorials> conferenceEditorialses, Set<ConferencePapers> conferencePaperses,
			Set<JournalEditorials> journalEditorialses, Set<JournalPapers> journalPaperses) {
		this.id = id;
		this.conferences = conferences;
		this.journals = journals;
		this.publisherName = publisherName;
		this.volume = volume;
		this.number = number;
		this.bookChapterses = bookChapterses;
		this.bookses = bookses;
		this.conferenceEditorialses = conferenceEditorialses;
		this.conferencePaperses = conferencePaperses;
		this.journalEditorialses = journalEditorialses;
		this.journalPaperses = journalPaperses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public String getPublisherName() {
		return this.publisherName;
	}

	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}


//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "conference_id")
	public Conferences getConferences() {
		return this.conferences;
	}

	public void setConferences(Conferences conferences) {
		this.conferences = conferences;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "journal_id")
	public Journals getJournals() {
		return this.journals;
	}

	public void setJournals(Journals journals) {
		this.journals = journals;
	}

	@Column(name = "volume")
	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	@Column(name = "number")
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@JsonIgnore
	public Set<ConferenceEditorials> getConferenceEditorialses() {
		return this.conferenceEditorialses;
	}

	public void setConferenceEditorialses(Set<ConferenceEditorials> conferenceEditorialses) {
		this.conferenceEditorialses = conferenceEditorialses;
	}

	@JsonIgnore
	public Set<ConferencePapers> getConferencePaperses() {
		return this.conferencePaperses;
	}

	public void setConferencePaperses(Set<ConferencePapers> conferencePaperses) {
		this.conferencePaperses = conferencePaperses;
	}

	@JsonIgnore
	public Set<JournalEditorials> getJournalEditorialses() {
		return this.journalEditorialses;
	}

	public void setJournalEditorialses(Set<JournalEditorials> journalEditorialses) {
		this.journalEditorialses = journalEditorialses;
	}

	@JsonIgnore
	public Set<JournalPapers> getJournalPaperses() {
		return this.journalPaperses;
	}

	public void setJournalPaperses(Set<JournalPapers> journalPaperses) {
		this.journalPaperses = journalPaperses;
	}
	
	@JsonIgnore
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}
	
	@JsonIgnore
	public Set<BookChapters> getBookChapterses() {
		return this.bookChapterses;
	}

	public void setBookChapterses(Set<BookChapters> bookChapterses) {
		this.bookChapterses = bookChapterses;
	}

}
