package com.slr.app.models;
// Generated Jun 22, 2020, 3:24:17 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;


/**
 * Publications generated by hbm2java
 */
@Entity
@Table(name = "publications", schema = "slr")
@JsonIgnoreProperties({"hibernateLazyinitializer","handler"})
public class Publications implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	//@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "pub_sequence")
	//@SequenceGenerator(name = "pub_sequence", sequenceName = "slr.publications_id_seq", allocationSize = 1 )
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private long id;

	@Column(name = "abstract",nullable = true)
	private String abstract_;
	
	private String title;
	private String dblpKey;
	private Integer year;
	private String url;
	private String ee;
	private String note;
	private String crossref;
	private Date mdate;
	private String updatedState;
	private String docType;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "reg_date", length = 13)
	private Date regDate;
	
	@Column(name="rg_info")
	private String rgInfo;
	
	@Column(name="proceeding_info")
	private String proceedingInfo;
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	//private Set<BookChapters> bookChapterses = new HashSet<BookChapters>(0);
	@OneToOne(mappedBy = "publications",cascade = CascadeType.PERSIST)
	private BookChapters bookChapters;
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	//private Set<JournalEditorials> journalEditorialses = new HashSet<JournalEditorials>(0);
	@OneToOne(mappedBy = "publications",cascade = CascadeType.PERSIST)
	private JournalEditorials JournalEditorials;
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	//private Set<ConferenceEditorials> conferenceEditorialses = new HashSet<ConferenceEditorials>(0);
	@OneToOne(mappedBy = "publications",cascade = CascadeType.PERSIST)
	private ConferenceEditorials conferenceEditorials;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications", cascade = CascadeType.PERSIST)
	private Set<AuthorPublications> authorPublicationses = new HashSet<AuthorPublications>(0);
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	//private Set<ConferencePapers> conferencePaperses = new HashSet<ConferencePapers>(0);
	@OneToOne(mappedBy = "publications",cascade = CascadeType.PERSIST)
	private ConferencePapers conferencePapers;
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	//private Set<Books> bookses = new HashSet<Books>(0);
	@OneToOne(mappedBy = "publications", cascade = CascadeType.PERSIST)
	private Books books;
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	//private Set<JournalPapers> journalPaperses = new HashSet<JournalPapers>(0);
	@OneToOne(mappedBy = "publications",cascade = CascadeType.PERSIST)
	private JournalPapers journalPapers;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	private Set<PublicationKeywords> publicationKeywordses = new HashSet<PublicationKeywords>(0);

	public Publications() {
	}

	public Publications(long id) {
		this.id = id;
	}

	public Publications(long id, String abstract_, String title, String dblpKey, Integer year, String url, String ee,
			String note, String crossref, Date mdate, String updatedState, String docType, Date regDate,
			//Set<BookChapters> bookChapterses, 
			BookChapters bookChapters,
			//Set<JournalEditorials> journalEditorialses,
			JournalEditorials journalEditorials,
			//Set<ConferenceEditorials> conferenceEditorialses,
			ConferenceEditorials conferenceEditorials,
			Set<AuthorPublications> authorPublicationses,
			//Set<ConferencePapers> conferencePaperses,
			ConferencePapers conferencePapers,
			//Set<Books> bookses,
			Books books,
			//Set<JournalPapers> journalPaperses,
			JournalPapers journalPapers,
			Set<PublicationKeywords> publicationKeywordses) {
		this.id = id;
		this.abstract_ = abstract_;
		this.title = title;
		this.dblpKey = dblpKey;
		this.year = year;
		this.url = url;
		this.ee = ee;
		this.note = note;
		this.crossref = crossref;
		this.mdate = mdate;
		this.updatedState = updatedState;
		this.docType = docType;
		this.regDate = regDate;
		//this.bookChapterses = bookChapterses;
		this.bookChapters = bookChapters;
		//this.journalEditorialses = journalEditorialses;
		this.JournalEditorials = journalEditorials;		
		//this.conferenceEditorialses = conferenceEditorialses;
		this.conferenceEditorials = conferenceEditorials;
		this.authorPublicationses = authorPublicationses;
		//this.conferencePaperses = conferencePaperses;
		this.conferencePapers = conferencePapers;
		//this.bookses = bookses;
		this.books = books;
		//this.journalPaperses = journalPaperses;
		this.journalPapers = journalPapers;
		this.publicationKeywordses = publicationKeywordses;
	}

	
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getAbstract_() {
		return this.abstract_;
	}
	
	public void setAbstract_(String abstract_) {
		this.abstract_ = abstract_;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "dblp_key", length = 100)
	public String getDblpKey() {
		return this.dblpKey;
	}

	public void setDblpKey(String dblpKey) {
		this.dblpKey = dblpKey;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ee")
	public String getEe() {
		return this.ee;
	}

	public void setEe(String ee) {
		this.ee = ee;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "crossref")
	public String getCrossref() {
		return this.crossref;
	}

	public void setCrossref(String crossref) {
		this.crossref = crossref;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mdate", length = 13)
	public Date getMdate() {
		return this.mdate;
	}

	public void setMdate(Date mdate) {
		this.mdate = mdate;
	}

	@Column(name = "updated_state", length = 80)
	public String getUpdatedState() {
		return this.updatedState;
	}

	public void setUpdatedState(String updatedState) {
		this.updatedState = updatedState;
	}

	@Column(name = "doc_type", length = 80)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}
	
	
	
//	public Set<BookChapters> getBookChapterses() {
//		return this.bookChapterses;
//	}
//
//	public void setBookChapterses(Set<BookChapters> bookChapterses) {
//		this.bookChapterses = bookChapterses;
//	}
//
//	public Set<JournalEditorials> getJournalEditorialses() {
//		return this.journalEditorialses;
//	}
//
//	public void setJournalEditorialses(Set<JournalEditorials> journalEditorialses) {
//		this.journalEditorialses = journalEditorialses;
//	}
//
//	public Set<ConferenceEditorials> getConferenceEditorialses() {
//		return this.conferenceEditorialses;
//	}
//
//	public void setConferenceEditorialses(Set<ConferenceEditorials> conferenceEditorialses) {
//		this.conferenceEditorialses = conferenceEditorialses;
//	}


	public String getRgInfo() {
		return rgInfo;
	}

	public void setRgInfo(String rgInfo) {
		this.rgInfo = rgInfo;
	}

	public String getProceedingInfo() {
		return proceedingInfo;
	}

	public void setProceedingInfo(String proceedingInfo) {
		this.proceedingInfo = proceedingInfo;
	}

	public BookChapters getBookChapters() {
		return bookChapters;
	}

	public void setBookChapters(BookChapters bookChapters) {
		this.bookChapters = bookChapters;
	}
	
	public JournalEditorials getJournalEditorials() {
		return JournalEditorials;
	}

	public void setJournalEditorials(JournalEditorials journalEditorials) {
		JournalEditorials = journalEditorials;
	}
	
	public ConferenceEditorials getConferenceEditorials() {
		return conferenceEditorials;
	}

	public void setConferenceEditorials(ConferenceEditorials conferenceEditorials) {
		this.conferenceEditorials = conferenceEditorials;
	}
	
	public ConferencePapers getConferencePapers() {
		return conferencePapers;
	}

	public void setConferencePapers(ConferencePapers conferencePapers) {
		this.conferencePapers = conferencePapers;
	}
	@JsonManagedReference
	public Books getBooks() {
		return books;
	}

	public void setBooks(Books books) {
		this.books = books;
	}
	public JournalPapers getJournalPapers() {
		return journalPapers;
	}

	public void setJournalPapers(JournalPapers journalPapers) {
		this.journalPapers = journalPapers;
	}
	@JsonManagedReference
	public Set<AuthorPublications> getAuthorPublicationses() {
		return this.authorPublicationses;
	}

	public void setAuthorPublicationses(Set<AuthorPublications> authorPublicationses) {
		this.authorPublicationses = authorPublicationses;
	}

//	public Set<ConferencePapers> getConferencePaperses() {
//		return this.conferencePaperses;
//	}
//
//	public void setConferencePaperses(Set<ConferencePapers> conferencePaperses) {
//		this.conferencePaperses = conferencePaperses;
//	}

//	public Set<Books> getBookses() {
//		return this.bookses;
//	}
//
//	public void setBookses(Set<Books> bookses) {
//		this.bookses = bookses;
//	}

//	public Set<JournalPapers> getJournalPaperses() {
//		return this.journalPaperses;
//	}
//
//	public void setJournalPaperses(Set<JournalPapers> journalPaperses) {
//		this.journalPaperses = journalPaperses;
//	}
	
	@JsonManagedReference
	public Set<PublicationKeywords> getPublicationKeywordses() {
		return this.publicationKeywordses;
	}

	public void setPublicationKeywordses(Set<PublicationKeywords> publicationKeywordses) {
		this.publicationKeywordses = publicationKeywordses;
	}

	//funcion que extrae DOI de una publicacion
	public String extractDOI()
	{
		String res = getEe();
		String doi = "https://doi.org/";
			
		if(!res.isEmpty())
		{
			if(res.contains(doi))
			{
				res = res.substring(doi.length(), res.length());
			}else
				res = "";
		}
		return res;
	}
	
	@Override
	public String toString() {

	    return String.valueOf(getId());
	}
}
