package com.slr.app.models;
// Generated Jun 22, 2020, 3:24:17 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Publishers generated by hbm2java
 */
@Entity
@Table(name = "publishers", schema = "slr")
@JsonIgnoreProperties({"hibernateLazyinitializer","handler"})
public class Publishers implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private long id;
	
	private String description;
	private String state;
	private Date createdAt;
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "publishers")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publishers")
	private Set<Books> bookses = new HashSet<Books>(0);
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "publishers")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publishers",cascade = CascadeType.ALL)
	private Set<BookChapters> bookChapterses = new HashSet<BookChapters>(0);
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "publishers")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publishers",cascade = CascadeType.ALL)
	private Set<Editions> editionses = new HashSet<Editions>(0);
	
	public Publishers() {
	}

	public Publishers(long id) {
		this.id = id;
	}

	public Publishers(long id, String description, String state, Date createdAt, Set<BookChapters> bookChapterses,
			Set<Editions> editionses, Set<Books> bookses) {
		this.id = id;
		this.description = description;
		this.state = state;
		this.createdAt = createdAt;
		this.bookChapterses = bookChapterses;
		this.editionses = editionses;
		this.bookses = bookses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "state", length = 200)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	
	@JsonManagedReference
	public Set<BookChapters> getBookChapterses() {
		return this.bookChapterses;
	}

	public void setBookChapterses(Set<BookChapters> bookChapterses) {
		this.bookChapterses = bookChapterses;
	}
	
	@JsonManagedReference
	public Set<Editions> getEditionses() {
		return this.editionses;
	}
	
	public void setEditionses(Set<Editions> editionses) {
		this.editionses = editionses;
	}

	@JsonManagedReference
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

}
