package com.slr.app.models;
// Generated Jun 22, 2021 11:00:33 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuthorPublications generated by hbm2java
 */
@Entity
@Table(name = "author_publications", schema = "slr")
public class AuthorPublications implements java.io.Serializable {

	private long id;
	private Authors authors;
	private Publications publications;
	private Integer herarchy;
	private Date createdAt;

	public AuthorPublications() {
	}

	public AuthorPublications(long id) {
		this.id = id;
	}

	public AuthorPublications(long id, Authors authors, Publications publications, Integer herarchy, Date createdAt) {
		this.id = id;
		this.authors = authors;
		this.publications = publications;
		this.herarchy = herarchy;
		this.createdAt = createdAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id")
	public Authors getAuthors() {
		return this.authors;
	}

	public void setAuthors(Authors authors) {
		this.authors = authors;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publication_id")
	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	@Column(name = "herarchy")
	public Integer getHerarchy() {
		return this.herarchy;
	}

	public void setHerarchy(Integer herarchy) {
		this.herarchy = herarchy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
