package com.slr.app.models;
// Generated Apr 3, 2021 6:46:22 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Authors generated by hbm2java
 */
@Entity
@Table(name = "authors", schema = "slr")
public class Authors implements java.io.Serializable {

	private long id;
	private Departments departments;
	private String key;
	private String pid;
	private String position;
	private String skills;
	private String disciplines;
	private String names;
	private Serializable homonyns;
	private Serializable urls;
	private Serializable cites;
	private Date createdAt;
	private Serializable awards;
	private String affiliation;
	private String mdate;
	private Integer insertGroup;

	public Authors() {
	}

	public Authors(long id, String names) {
		this.id = id;
		this.names = names;
	}

	public Authors(long id, Departments departments, String key, String pid, String position, String skills,
			String disciplines, String names, Serializable homonyns, Serializable urls, Serializable cites,
			Date createdAt, Serializable awards, String affiliation, String mdate, Integer insertGroup) {
		this.id = id;
		this.departments = departments;
		this.key = key;
		this.pid = pid;
		this.position = position;
		this.skills = skills;
		this.disciplines = disciplines;
		this.names = names;
		this.homonyns = homonyns;
		this.urls = urls;
		this.cites = cites;
		this.createdAt = createdAt;
		this.awards = awards;
		this.affiliation = affiliation;
		this.mdate = mdate;
		this.insertGroup = insertGroup;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "department_id")
	public Departments getDepartments() {
		return this.departments;
	}

	public void setDepartments(Departments departments) {
		this.departments = departments;
	}

	@Column(name = "key")
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "pid")
	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	@Column(name = "position")
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "skills")
	public String getSkills() {
		return this.skills;
	}

	public void setSkills(String skills) {
		this.skills = skills;
	}

	@Column(name = "disciplines")
	public String getDisciplines() {
		return this.disciplines;
	}

	public void setDisciplines(String disciplines) {
		this.disciplines = disciplines;
	}

	@Column(name = "names", nullable = false)
	public String getNames() {
		return this.names;
	}

	public void setNames(String names) {
		this.names = names;
	}

	@Column(name = "homonyns")
	public Serializable getHomonyns() {
		return this.homonyns;
	}

	public void setHomonyns(Serializable homonyns) {
		this.homonyns = homonyns;
	}

	@Column(name = "urls")
	public Serializable getUrls() {
		return this.urls;
	}

	public void setUrls(Serializable urls) {
		this.urls = urls;
	}

	@Column(name = "cites")
	public Serializable getCites() {
		return this.cites;
	}

	public void setCites(Serializable cites) {
		this.cites = cites;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "awards")
	public Serializable getAwards() {
		return this.awards;
	}

	public void setAwards(Serializable awards) {
		this.awards = awards;
	}

	@Column(name = "affiliation")
	public String getAffiliation() {
		return this.affiliation;
	}

	public void setAffiliation(String affiliation) {
		this.affiliation = affiliation;
	}

	@Column(name = "mdate", length = 70)
	public String getMdate() {
		return this.mdate;
	}

	public void setMdate(String mdate) {
		this.mdate = mdate;
	}

	@Column(name = "insert_group")
	public Integer getInsertGroup() {
		return this.insertGroup;
	}

	public void setInsertGroup(Integer insertGroup) {
		this.insertGroup = insertGroup;
	}

}
