package com.slr.app.models;
// Generated Jun 22, 2021 11:00:33 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DblpUpdated generated by hbm2java
 */
@Entity
@Table(name = "dblp_updated", schema = "public")
public class DblpUpdated implements java.io.Serializable {

	private int id;
	private String keyDblp;
	private Serializable authors;
	private String docType;
	private String editor;
	private String pages;
	private Integer year;
	private String title;
	private String address;
	private String journal;
	private String volume;
	private String number;
	private String month;
	private String url;
	private String ee;
	private String cdrom;
	private String cite;
	private String publisher;
	private String note;
	private String crossref;
	private String isbn;
	private String series;
	private String school;
	private String chapter;
	private String publnr;
	private String bookTitle;
	private String mdate;
	private Date regDate;
	private String updatedState;
	private Integer grupo;
	private String proceedingInfo;

	public DblpUpdated() {
	}

	public DblpUpdated(int id) {
		this.id = id;
	}

	public DblpUpdated(int id, String keyDblp, Serializable authors, String docType, String editor, String pages,
			Integer year, String title, String address, String journal, String volume, String number, String month,
			String url, String ee, String cdrom, String cite, String publisher, String note, String crossref,
			String isbn, String series, String school, String chapter, String publnr, String bookTitle, String mdate,
			Date regDate, String updatedState, Integer grupo, String proceedingInfo) {
		this.id = id;
		this.keyDblp = keyDblp;
		this.authors = authors;
		this.docType = docType;
		this.editor = editor;
		this.pages = pages;
		this.year = year;
		this.title = title;
		this.address = address;
		this.journal = journal;
		this.volume = volume;
		this.number = number;
		this.month = month;
		this.url = url;
		this.ee = ee;
		this.cdrom = cdrom;
		this.cite = cite;
		this.publisher = publisher;
		this.note = note;
		this.crossref = crossref;
		this.isbn = isbn;
		this.series = series;
		this.school = school;
		this.chapter = chapter;
		this.publnr = publnr;
		this.bookTitle = bookTitle;
		this.mdate = mdate;
		this.regDate = regDate;
		this.updatedState = updatedState;
		this.grupo = grupo;
		this.proceedingInfo = proceedingInfo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "key_dblp", length = 200)
	public String getKeyDblp() {
		return this.keyDblp;
	}

	public void setKeyDblp(String keyDblp) {
		this.keyDblp = keyDblp;
	}

	@Column(name = "authors")
	public Serializable getAuthors() {
		return this.authors;
	}

	public void setAuthors(Serializable authors) {
		this.authors = authors;
	}

	@Column(name = "doc_type", length = 100)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "editor", length = 100)
	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	@Column(name = "pages", length = 100)
	public String getPages() {
		return this.pages;
	}

	public void setPages(String pages) {
		this.pages = pages;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "journal")
	public String getJournal() {
		return this.journal;
	}

	public void setJournal(String journal) {
		this.journal = journal;
	}

	@Column(name = "volume", length = 100)
	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	@Column(name = "number", length = 100)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "month", length = 100)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ee")
	public String getEe() {
		return this.ee;
	}

	public void setEe(String ee) {
		this.ee = ee;
	}

	@Column(name = "cdrom")
	public String getCdrom() {
		return this.cdrom;
	}

	public void setCdrom(String cdrom) {
		this.cdrom = cdrom;
	}

	@Column(name = "cite")
	public String getCite() {
		return this.cite;
	}

	public void setCite(String cite) {
		this.cite = cite;
	}

	@Column(name = "publisher")
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "crossref")
	public String getCrossref() {
		return this.crossref;
	}

	public void setCrossref(String crossref) {
		this.crossref = crossref;
	}

	@Column(name = "isbn")
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "series")
	public String getSeries() {
		return this.series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	@Column(name = "school")
	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	@Column(name = "chapter")
	public String getChapter() {
		return this.chapter;
	}

	public void setChapter(String chapter) {
		this.chapter = chapter;
	}

	@Column(name = "publnr")
	public String getPublnr() {
		return this.publnr;
	}

	public void setPublnr(String publnr) {
		this.publnr = publnr;
	}

	@Column(name = "book_title")
	public String getBookTitle() {
		return this.bookTitle;
	}

	public void setBookTitle(String bookTitle) {
		this.bookTitle = bookTitle;
	}

	@Column(name = "mdate", length = 100)
	public String getMdate() {
		return this.mdate;
	}

	public void setMdate(String mdate) {
		this.mdate = mdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reg_date", length = 13)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "updated_state", length = 100)
	public String getUpdatedState() {
		return this.updatedState;
	}

	public void setUpdatedState(String updatedState) {
		this.updatedState = updatedState;
	}

	@Column(name = "grupo")
	public Integer getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Integer grupo) {
		this.grupo = grupo;
	}

	@Column(name = "proceeding_info", length = 100)
	public String getProceedingInfo() {
		return this.proceedingInfo;
	}

	public void setProceedingInfo(String proceedingInfo) {
		this.proceedingInfo = proceedingInfo;
	}

}
