package com.slr.app.models;
// Generated Apr 3, 2021 6:46:22 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Journals generated by hbm2java
 */
@Entity
@Table(name = "journals", schema = "slr")
public class Journals implements java.io.Serializable {

	private long id;
	private String name;
	private String abreviation;
	private Date createdAt;
	private Set<Editions> editionses = new HashSet<Editions>(0);

	public Journals() {
	}

	public Journals(long id) {
		this.id = id;
	}

	public Journals(long id, String name, String abreviation, Date createdAt, Set<Editions> editionses) {
		this.id = id;
		this.name = name;
		this.abreviation = abreviation;
		this.createdAt = createdAt;
		this.editionses = editionses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "abreviation")
	public String getAbreviation() {
		return this.abreviation;
	}

	public void setAbreviation(String abreviation) {
		this.abreviation = abreviation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "journals")
	public Set<Editions> getEditionses() {
		return this.editionses;
	}

	public void setEditionses(Set<Editions> editionses) {
		this.editionses = editionses;
	}

}
