package com.slr.app.models;
// Generated Apr 3, 2021 6:46:22 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publishers generated by hbm2java
 */
@Entity
@Table(name = "publishers", schema = "slr")
public class Publishers implements java.io.Serializable {

	private long id;
	private String description;
	private String state;
	private Date createdAt;
	private Set<BookChapters> bookChapterses = new HashSet<BookChapters>(0);
	private Set<Editions> editionses = new HashSet<Editions>(0);
	private Set<Books> bookses = new HashSet<Books>(0);

	public Publishers() {
	}

	public Publishers(long id) {
		this.id = id;
	}

	public Publishers(long id, String description, String state, Date createdAt, Set<BookChapters> bookChapterses,
			Set<Editions> editionses, Set<Books> bookses) {
		this.id = id;
		this.description = description;
		this.state = state;
		this.createdAt = createdAt;
		this.bookChapterses = bookChapterses;
		this.editionses = editionses;
		this.bookses = bookses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "state", length = 200)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publishers")
	public Set<BookChapters> getBookChapterses() {
		return this.bookChapterses;
	}

	public void setBookChapterses(Set<BookChapters> bookChapterses) {
		this.bookChapterses = bookChapterses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publishers")
	public Set<Editions> getEditionses() {
		return this.editionses;
	}

	public void setEditionses(Set<Editions> editionses) {
		this.editionses = editionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publishers")
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

}
