package com.slr.app.models;
// Generated Apr 3, 2021 6:46:22 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publications generated by hbm2java
 */
@Entity
@Table(name = "publications", schema = "slr")
public class Publications implements java.io.Serializable {

	private long id;
	private String abstract_;
	private String title;
	private String dblpKey;
	private Integer year;
	private String url;
	private String ee;
	private String note;
	private String crossref;
	private Date mdate;
	private String updatedState;
	private String docType;
	private Date regDate;
	private String rgInfo;
	private String proceedingInfo;
	private Set<BookChapters> bookChapterses = new HashSet<BookChapters>(0);
	private Set<JournalEditorials> journalEditorialses = new HashSet<JournalEditorials>(0);
	private Set<ConferenceEditorials> conferenceEditorialses = new HashSet<ConferenceEditorials>(0);
	private Set<AuthorPublications> authorPublicationses = new HashSet<AuthorPublications>(0);
	private Set<ConferencePapers> conferencePaperses = new HashSet<ConferencePapers>(0);
	private Set<Books> bookses = new HashSet<Books>(0);
	private Set<JournalPapers> journalPaperses = new HashSet<JournalPapers>(0);
	private Set<PublicationKeywords> publicationKeywordses = new HashSet<PublicationKeywords>(0);

	public Publications() {
	}

	public Publications(long id) {
		this.id = id;
	}

	public Publications(long id, String abstract_, String title, String dblpKey, Integer year, String url, String ee,
			String note, String crossref, Date mdate, String updatedState, String docType, Date regDate, String rgInfo,
			String proceedingInfo, Set<BookChapters> bookChapterses, Set<JournalEditorials> journalEditorialses,
			Set<ConferenceEditorials> conferenceEditorialses, Set<AuthorPublications> authorPublicationses,
			Set<ConferencePapers> conferencePaperses, Set<Books> bookses, Set<JournalPapers> journalPaperses,
			Set<PublicationKeywords> publicationKeywordses) {
		this.id = id;
		this.abstract_ = abstract_;
		this.title = title;
		this.dblpKey = dblpKey;
		this.year = year;
		this.url = url;
		this.ee = ee;
		this.note = note;
		this.crossref = crossref;
		this.mdate = mdate;
		this.updatedState = updatedState;
		this.docType = docType;
		this.regDate = regDate;
		this.rgInfo = rgInfo;
		this.proceedingInfo = proceedingInfo;
		this.bookChapterses = bookChapterses;
		this.journalEditorialses = journalEditorialses;
		this.conferenceEditorialses = conferenceEditorialses;
		this.authorPublicationses = authorPublicationses;
		this.conferencePaperses = conferencePaperses;
		this.bookses = bookses;
		this.journalPaperses = journalPaperses;
		this.publicationKeywordses = publicationKeywordses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "abstract")
	public String getAbstract_() {
		return this.abstract_;
	}

	public void setAbstract_(String abstract_) {
		this.abstract_ = abstract_;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "dblp_key", length = 100)
	public String getDblpKey() {
		return this.dblpKey;
	}

	public void setDblpKey(String dblpKey) {
		this.dblpKey = dblpKey;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ee")
	public String getEe() {
		return this.ee;
	}

	public void setEe(String ee) {
		this.ee = ee;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "crossref")
	public String getCrossref() {
		return this.crossref;
	}

	public void setCrossref(String crossref) {
		this.crossref = crossref;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mdate", length = 13)
	public Date getMdate() {
		return this.mdate;
	}

	public void setMdate(Date mdate) {
		this.mdate = mdate;
	}

	@Column(name = "updated_state", length = 80)
	public String getUpdatedState() {
		return this.updatedState;
	}

	public void setUpdatedState(String updatedState) {
		this.updatedState = updatedState;
	}

	@Column(name = "doc_type", length = 80)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reg_date", length = 13)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "rg_info")
	public String getRgInfo() {
		return this.rgInfo;
	}

	public void setRgInfo(String rgInfo) {
		this.rgInfo = rgInfo;
	}

	@Column(name = "proceeding_info", length = 100)
	public String getProceedingInfo() {
		return this.proceedingInfo;
	}

	public void setProceedingInfo(String proceedingInfo) {
		this.proceedingInfo = proceedingInfo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	public Set<BookChapters> getBookChapterses() {
		return this.bookChapterses;
	}

	public void setBookChapterses(Set<BookChapters> bookChapterses) {
		this.bookChapterses = bookChapterses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	public Set<JournalEditorials> getJournalEditorialses() {
		return this.journalEditorialses;
	}

	public void setJournalEditorialses(Set<JournalEditorials> journalEditorialses) {
		this.journalEditorialses = journalEditorialses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	public Set<ConferenceEditorials> getConferenceEditorialses() {
		return this.conferenceEditorialses;
	}

	public void setConferenceEditorialses(Set<ConferenceEditorials> conferenceEditorialses) {
		this.conferenceEditorialses = conferenceEditorialses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	public Set<AuthorPublications> getAuthorPublicationses() {
		return this.authorPublicationses;
	}

	public void setAuthorPublicationses(Set<AuthorPublications> authorPublicationses) {
		this.authorPublicationses = authorPublicationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	public Set<ConferencePapers> getConferencePaperses() {
		return this.conferencePaperses;
	}

	public void setConferencePaperses(Set<ConferencePapers> conferencePaperses) {
		this.conferencePaperses = conferencePaperses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	public Set<JournalPapers> getJournalPaperses() {
		return this.journalPaperses;
	}

	public void setJournalPaperses(Set<JournalPapers> journalPaperses) {
		this.journalPaperses = journalPaperses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publications")
	public Set<PublicationKeywords> getPublicationKeywordses() {
		return this.publicationKeywordses;
	}

	public void setPublicationKeywordses(Set<PublicationKeywords> publicationKeywordses) {
		this.publicationKeywordses = publicationKeywordses;
	}

}
