package com.slr.app.models;
// Generated Jun 22, 2021 11:00:33 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PublicationKeywords generated by hbm2java
 */
@Entity
@Table(name = "publication_keywords", schema = "slr")
public class PublicationKeywords implements java.io.Serializable {

	private long id;
	private Keywords keywords;
	private Publications publications;
	private Date createdAt;

	public PublicationKeywords() {
	}

	public PublicationKeywords(long id) {
		this.id = id;
	}

	public PublicationKeywords(long id, Keywords keywords, Publications publications, Date createdAt) {
		this.id = id;
		this.keywords = keywords;
		this.publications = publications;
		this.createdAt = createdAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "keyword_id")
	public Keywords getKeywords() {
		return this.keywords;
	}

	public void setKeywords(Keywords keywords) {
		this.keywords = keywords;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publication_id")
	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
