package com.slr.app.models;
// Generated Jun 22, 2021 11:00:33 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpApis generated by hbm2java
 */
@Entity
@Table(name = "tmp_apis", schema = "public")
public class TmpApis implements java.io.Serializable {

	private String keyDblp;
	private String api;
	private String searchParams;
	private Integer group;
	private Boolean updated;
	private Serializable data;
	private Date regDate;

	public TmpApis() {
	}

	public TmpApis(String keyDblp) {
		this.keyDblp = keyDblp;
	}

	public TmpApis(String keyDblp, String api, String searchParams, Integer group, Boolean updated, Serializable data,
			Date regDate) {
		this.keyDblp = keyDblp;
		this.api = api;
		this.searchParams = searchParams;
		this.group = group;
		this.updated = updated;
		this.data = data;
		this.regDate = regDate;
	}

	@Id

	@Column(name = "key_dblp", unique = true, nullable = false, length = 100)
	public String getKeyDblp() {
		return this.keyDblp;
	}

	public void setKeyDblp(String keyDblp) {
		this.keyDblp = keyDblp;
	}

	@Column(name = "api", length = 30)
	public String getApi() {
		return this.api;
	}

	public void setApi(String api) {
		this.api = api;
	}

	@Column(name = "search_params", length = 500)
	public String getSearchParams() {
		return this.searchParams;
	}

	public void setSearchParams(String searchParams) {
		this.searchParams = searchParams;
	}

	@Column(name = "group")
	public Integer getGroup() {
		return this.group;
	}

	public void setGroup(Integer group) {
		this.group = group;
	}

	@Column(name = "updated")
	public Boolean getUpdated() {
		return this.updated;
	}

	public void setUpdated(Boolean updated) {
		this.updated = updated;
	}

	@Column(name = "data")
	public Serializable getData() {
		return this.data;
	}

	public void setData(Serializable data) {
		this.data = data;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reg_date", length = 13)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
