package com.slr.app.models;
// Generated Jun 22, 2021 11:00:33 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TmpTest generated by hbm2java
 */
@Entity
@Table(name = "tmp_test", schema = "public")
public class TmpTest implements java.io.Serializable {

	private Serializable row1;

	public TmpTest() {
	}

	public TmpTest(Serializable row1) {
		this.row1 = row1;
	}

	@Id

	@Column(name = "row1")
	public Serializable getRow1() {
		return this.row1;
	}

	public void setRow1(Serializable row1) {
		this.row1 = row1;
	}

}
